#!/usr/bin/env python3
"""CS Party board compiler.

Turns any CS 1.6 map that has a zBot navigation mesh (.nav, generated by ReGameDLL's
built-in bots on first load) into a Mario Party style board:

  T spawn -> bombsite B -> CT spawn -> bombsite A -> back to T spawn   (main loop)
  plus one shortcut branch that the loop didn't use (on de_dust2 that's mid doors).

Each leg is an A* path over nav areas; areas used by earlier legs are penalised so
the loop runs through different corridors instead of doubling back. Spaces are
sampled at even distances along the paths and written to an .ini the AMXX plugin
reads. Optionally renders a PNG overview for checking.

usage: board_compiler.py <cstrike_dir> <map> [--out boards/<map>.ini] [--png out.png]
"""
import argparse, heapq, math, os, re, struct, sys

# ---------------------------------------------------------------- nav ----
NAV_MAGIC = 0xFEEDFACE

class Area:
    __slots__ = ("id", "flags", "lo", "hi", "nez", "swz", "conn", "place")
    def center(self):
        return ((self.lo[0] + self.hi[0]) / 2, (self.lo[1] + self.hi[1]) / 2,
                (self.lo[2] + self.hi[2] + self.nez + self.swz) / 4)
    def z_at(self, x, y):
        # bilinear over the 4 corners: nw=lo.z, se=hi.z, ne=nez, sw=swz
        w = max(1e-3, self.hi[0] - self.lo[0]); h = max(1e-3, self.hi[1] - self.lo[1])
        u = min(1, max(0, (x - self.lo[0]) / w)); v = min(1, max(0, (y - self.lo[1]) / h))
        nw, ne, sw, se = self.lo[2], self.nez, self.swz, self.hi[2]
        return (nw * (1 - u) + ne * u) * (1 - v) + (sw * (1 - u) + se * u) * v
    def contains(self, x, y, pad=0):
        return self.lo[0] - pad <= x <= self.hi[0] + pad and self.lo[1] - pad <= y <= self.hi[1] + pad

def read_nav(path):
    b = open(path, "rb").read(); o = 0
    def rd(fmt):
        nonlocal o
        v = struct.unpack_from("<" + fmt, b, o); o += struct.calcsize("<" + fmt)
        return v if len(v) > 1 else v[0]
    magic = rd("I")
    if magic != NAV_MAGIC: sys.exit(f"{path}: not a nav file")
    version = rd("I")
    if version >= 4: rd("I")                       # bsp size
    places = []
    if version >= 5:
        n = rd("H")
        for _ in range(n):
            ln = rd("H"); places.append(b[o:o + ln].split(b"\0")[0].decode(errors="replace")); o += ln
    areas = {}
    for _ in range(rd("I")):
        a = Area(); a.id = rd("I"); a.flags = rd("B")
        e = rd("6f"); a.lo, a.hi = e[:3], e[3:]
        a.nez, a.swz = rd("2f"); a.conn = []
        for d in range(4):
            for _ in range(rd("I")): a.conn.append(rd("I"))
        for _ in range(rd("B")): rd("I"); rd("3f"); rd("B")          # hiding spots
        for _ in range(rd("B")): rd("I"); rd("I"); rd("B"); rd("I"); rd("B")  # approach
        for _ in range(rd("I")):                                       # encounter paths
            rd("I"); rd("B"); rd("I"); rd("B")
            for _ in range(rd("B")): rd("I"); rd("B")
        pe = rd("H")
        a.place = places[pe - 1] if 0 < pe <= len(places) else ""
        areas[a.id] = a
    return areas

# ---------------------------------------------------------------- bsp ----
def read_bsp(path):
    b = open(path, "rb").read()
    ver = struct.unpack_from("<i", b, 0)[0]
    lumps = [struct.unpack_from("<ii", b, 4 + 8 * i) for i in range(15)]
    eo, el = lumps[0]
    text = b[eo:eo + el].decode("latin-1")
    ents = [dict(re.findall(r'"([^"]*)"\s+"([^"]*)"', blk)) for blk in re.findall(r"\{([^}]*)\}", text)]
    mo, ml = lumps[14]
    models = []
    for i in range(ml // 64):
        f = struct.unpack_from("<9f", b, mo + 64 * i); models.append((f[0:3], f[3:6]))
    return ver, ents, models

def vec(s): return tuple(float(x) for x in s.split())

# ---------------------------------------------------------------- graph --
def dist2(a, b): return math.hypot(a[0] - b[0], a[1] - b[1])

class Nav:
    def __init__(self, areas):
        self.A = areas
        self.C = {i: a.center() for i, a in areas.items()}
        self.adj = {i: set() for i in areas}
        for i, a in areas.items():
            for j in a.conn:
                if j in areas: self.adj[i].add(j); self.adj[j].add(i)   # pawns don't care about ledges
    def area_at(self, p):
        best = None; bd = 1e18
        for i, a in self.A.items():
            if a.contains(p[0], p[1]):
                dz = abs(a.z_at(p[0], p[1]) - p[2])
                if dz < bd: best, bd = i, dz
        if best is None:
            best = min(self.A, key=lambda i: dist2(self.C[i], p) + abs(self.C[i][2] - p[2]))
        return best
    def astar(self, s, t, penalty=None):
        penalty = penalty or {}
        C = self.C; g = {s: 0}; prev = {}; pq = [(0, s)]
        while pq:
            f, u = heapq.heappop(pq)
            if u == t: break
            for v in self.adj[u]:
                step = math.dist(C[u], C[v])
                ng = g[u] + step * (1 + penalty.get(v, 0))
                if ng < g.get(v, 1e18):
                    g[v] = ng; prev[v] = u
                    heapq.heappush(pq, (ng + math.dist(C[v], C[t]), v))
        if t not in g: return None
        path = [t]
        while path[-1] != s: path.append(prev[path[-1]])
        return path[::-1]

def polyline(nav, path):
    return [nav.C[i] for i in path]

def resample(pts, step, include_end=False):
    """points every `step` units along the polyline, starting at pts[0]."""
    out = [pts[0]]; need = step; i = 0; cur = pts[0]
    while i < len(pts) - 1:
        nxt = pts[i + 1]; seg = math.dist(cur, nxt)
        if seg >= need:
            t = need / seg
            cur = tuple(cur[k] + (nxt[k] - cur[k]) * t for k in range(3))
            out.append(cur); need = step
        else:
            need -= seg; cur = nxt; i += 1
    if include_end and math.dist(out[-1], pts[-1]) > step * 0.5: out.append(pts[-1])
    return out

def length(pts): return sum(math.dist(pts[i], pts[i + 1]) for i in range(len(pts) - 1))

# ---------------------------------------------------------------- build --
def build(cstrike, mapname, target_spaces=36, mid_spaces=6):
    navp = os.path.join(cstrike, "maps", mapname + ".nav")
    bspp = os.path.join(cstrike, "maps", mapname + ".bsp")
    nav = Nav(read_nav(navp)); _, ents, models = read_bsp(bspp)

    def centroid(cls):
        pts = [vec(e["origin"]) for e in ents if e.get("classname") == cls and "origin" in e]
        if not pts: return None
        return tuple(sum(p[k] for p in pts) / len(pts) for k in range(3))
    tsp, ctsp = centroid("info_player_deathmatch"), centroid("info_player_start")
    sites = []
    for e in ents:
        if e.get("classname") == "func_bomb_target" and e.get("model", "").startswith("*"):
            lo, hi = models[int(e["model"][1:])]
            sites.append(tuple((lo[k] + hi[k]) / 2 for k in range(3)))
        elif e.get("classname") == "info_bomb_target" and "origin" in e:
            sites.append(vec(e["origin"]))
    if not (tsp and ctsp and len(sites) >= 2):
        sys.exit("need T spawns, CT spawns and two bomb targets")

    aT, aCT = nav.area_at(tsp), nav.area_at(ctsp)
    sA = [nav.area_at(s) for s in sites[:2]]
    # site closer to CT spawn (by walking) is A
    d0 = len(nav.astar(aCT, sA[0]) or [0] * 999); d1 = len(nav.astar(aCT, sA[1]) or [0] * 999)
    (aA, pA), (aB, pB) = ((sA[0], sites[0]), (sA[1], sites[1])) if d0 <= d1 else ((sA[1], sites[1]), (sA[0], sites[0]))

    # legs with corridor penalties so the loop doesn't reuse paths
    used = {}
    def mark(path, w=6.0, radius=380):
        pts = [nav.C[i] for i in path]
        for j, c in nav.C.items():
            if any(dist2(c, p) < radius and abs(c[2] - p[2]) < 120 for p in pts[::2]):
                used[j] = max(used.get(j, 0), w)
    legs = []
    for s, t in ((aT, aB), (aB, aCT), (aCT, aA), (aA, aT)):
        pen = {k: v for k, v in used.items() if k not in (s, t)}
        p = nav.astar(s, t, pen); legs.append(p); mark(p)
    loop_pts = []
    for p in legs:
        pts = polyline(nav, p); loop_pts += pts if not loop_pts else pts[1:]
    L = length(loop_pts); step = L / target_spaces
    main = resample(loop_pts, step)[:target_spaces]

    # shortcut: T spawn side -> CT spawn avoiding the loop
    mid = nav.astar(aT, aCT, {k: v * 3 for k, v in used.items() if k not in (aT, aCT)})
    mid_pts = polyline(nav, mid)
    def near_loop(p): return min(dist2(p, q) for q in loop_pts) < 260
    i0 = next((i for i, p in enumerate(mid_pts) if not near_loop(p)), 0)
    i1 = len(mid_pts) - 1 - next((i for i, p in enumerate(reversed(mid_pts)) if not near_loop(p)), 0)
    seg = mid_pts[max(0, i0 - 1): i1 + 2]
    jn = min(range(len(main)), key=lambda i: math.dist(main[i], seg[0]))
    tj = min(range(len(main)), key=lambda i: math.dist(main[i], seg[-1]))
    ml = length(seg); n_mid = max(3, min(mid_spaces, int(ml / step)))
    inner = resample([main[jn]] + seg[1:-1] + [main[tj]], length([main[jn]] + seg[1:-1] + [main[tj]]) / (n_mid + 1))[1:n_mid + 1]

    nodes = []
    N = len(main)
    for i, p in enumerate(main):
        nodes.append({"id": i, "pos": p, "next": [(i + 1) % N], "type": "blue"})
    for k, p in enumerate(inner):
        nid = N + k
        nodes.append({"id": nid, "pos": p, "next": [nid + 1 if k < len(inner) - 1 else tj], "type": "blue", "mid": True})
    nodes[jn]["next"].append(N)

    # snap z to the floor of the containing nav area
    for n in nodes:
        a = nav.A[nav.area_at(n["pos"])]; x, y, _ = n["pos"]
        n["pos"] = (round(x, 1), round(y, 1), round(a.z_at(x, y) + 2, 1))

    # types: base pattern first, then special spaces placed where they make sense on the map
    def nearest(p, ids): return min(ids, key=lambda i: math.dist(nodes[i]["pos"], p))
    main_ids = list(range(N))
    siteA, siteB = nearest(pA, main_ids), nearest(pB, main_ids)
    ctShop = nearest(ctsp, [i for i in main_ids if i not in (siteA, siteB, 0)])
    for i in main_ids:
        n = nodes[i]
        if i == 0: n["type"], n["letter"] = "shop", "T"          # T spawn: start + T buy zone
        elif i == siteA: n["type"], n["letter"] = "site", "A"
        elif i == siteB: n["type"], n["letter"] = "site", "B"
        elif i == ctShop: n["type"], n["letter"] = "shop", "CT"  # CT spawn buy zone
        elif i % 6 == 3: n["type"] = "event"
        elif i % 4 == 2: n["type"] = "red"
    pattern = ["red", "event", "blue", "red", "blue", "event", "blue"]
    for k in range(len(inner)):
        nodes[N + k]["type"] = pattern[k % len(pattern)]
    fixed = {0, siteA, siteB, ctShop, jn, tj}
    def place(kind, idx_pool):
        for i in idx_pool:
            if i not in fixed:
                nodes[i]["type"] = kind; nodes[i].pop("letter", None); fixed.add(i); return i
        return None
    def around(frac):          # main-loop indices ordered by distance from a fraction of the lap
        c = frac * N
        return sorted((i for i in main_ids), key=lambda i: min(abs(i - c), N - abs(i - c)))
    mid_ids = list(range(N, N + len(inner)))
    mid_order = sorted(mid_ids, key=lambda i: -abs(i - (N + len(inner) / 2)))   # far from the middle = near the doors
    place("camper", [mid_ids[-2]] if len(mid_ids) > 2 else mid_ids)          # mid doors AWPer
    place("camper", around(0.86))                                            # long A
    place("duel", [mid_ids[1]] if len(mid_ids) > 1 else around(0.3))
    place("duel", around(0.30))
    place("armory", around(0.14))
    place("armory", around(0.57))
    place("vip", around(0.42))
    place("negotiator", around(0.72))
    # area names for HUD text
    anchors = [("T Spawn", tsp), ("CT Spawn", ctsp), ("A Site", pA), ("B Site", pB)]
    for n in nodes:
        name, d = min(((nm, math.dist(n["pos"], p)) for nm, p in anchors), key=lambda x: x[1])
        n["area"] = "Mid" if n.get("mid") else (name if d < 900 else "")
    # fill gaps with "<a> - <b>" style names by leg
    leg_names = ["Tunnels", "B to CT", "CT to A", "Long"]
    cuts = []; acc = 0
    for p in legs:
        acc += length(polyline(nav, p)); cuts.append(acc)
    for i in main_ids:
        if nodes[i]["area"]: continue
        d = i * step; leg = next((k for k, c in enumerate(cuts) if d <= c), 3)
        nodes[i]["area"] = leg_names[leg]

    return {"map": mapname, "nodes": nodes, "junction": jn, "join": tj, "step": step,
            "spawns": {"T": tsp, "CT": ctsp}, "sites": {"A": pA, "B": pB}, "nav": nav, "loop": loop_pts, "midseg": seg}

def write_ini(board, path):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w") as f:
        f.write(f"; CS Party board for {board['map']} — generated by board_compiler.py from the zBot nav mesh\n")
        f.write("; id  type   x y z   next(comma)   area\n")
        f.write(f"[board]\nmap={board['map']}\nnodes={len(board['nodes'])}\nstart=0\njunction={board['junction']}\njoin={board['join']}\n[nodes]\n")
        for n in board["nodes"]:
            x, y, z = n["pos"]
            t = n["type"] + (":" + n["letter"] if n.get("letter") else "")
            f.write(f'{n["id"]} {t} {x} {y} {z} {",".join(map(str, n["next"]))} "{n["area"]}"\n')

def render_png(board, path):
    import matplotlib; matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.patches import Rectangle
    nav = board["nav"]
    fig, ax = plt.subplots(figsize=(10, 10), dpi=110)
    fig.patch.set_facecolor("#121411"); ax.set_facecolor("#121411")
    for a in nav.A.values():
        ax.add_patch(Rectangle((a.lo[0], a.lo[1]), a.hi[0] - a.lo[0], a.hi[1] - a.lo[1], color="#4a4134", lw=0))
    col = {"blue": "#5d8fe8", "start": "#5d8fe8", "red": "#e2654c", "event": "#e7c74b", "site": "#f2a33a", "shop": "#7fd36b", "camper": "#7a1e14", "armory": "#4fd0c4", "vip": "#f4f1e6", "duel": "#b07cf0", "negotiator": "#ffd36b"}
    for n in board["nodes"]:
        for m in n["next"]:
            b = board["nodes"][m]["pos"]
            ax.plot([n["pos"][0], b[0]], [n["pos"][1], b[1]], color="#b99f6c", lw=1, ls=":")
    for n in board["nodes"]:
        x, y, _ = n["pos"]
        ax.scatter([x], [y], s=150 if n["type"] in ("site", "shop") else 90, c=col[n["type"]], edgecolors="#0e100c", linewidths=1.5, zorder=3)
        if n.get("letter"): ax.text(x, y, n["letter"], ha="center", va="center", fontsize=8, weight="bold", zorder=4)
        if n["id"] == 0: ax.scatter([x], [y], s=380, facecolors="none", edgecolors="#ddd7c4", linestyle="--", zorder=2)
        ax.text(x + 40, y + 40, str(n["id"]), color="#8d8876", fontsize=6)
    for nm, p in (("T", board["spawns"]["T"]), ("CT", board["spawns"]["CT"])):
        ax.text(p[0], p[1] - 160, nm + " spawn", color="#ddd7c4", ha="center", fontsize=9)
    ax.set_aspect("equal"); ax.axis("off")
    ax.set_title(f"{board['map']} board · {len(board['nodes'])} spaces", color="#f2a33a", fontsize=13)
    fig.savefig(path, bbox_inches="tight", facecolor=fig.get_facecolor()); plt.close(fig)

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("cstrike"); ap.add_argument("map")
    ap.add_argument("--out"); ap.add_argument("--png"); ap.add_argument("--spaces", type=int, default=36)
    a = ap.parse_args()
    bd = build(a.cstrike, a.map, a.spaces)
    out = a.out or os.path.join("boards", a.map + ".ini")
    write_ini(bd, out)
    if a.png: render_png(bd, a.png)
    types = {}
    for n in bd["nodes"]: types[n["type"]] = types.get(n["type"], 0) + 1
    print(f"{a.map}: {len(bd['nodes'])} spaces, step {bd['step']:.0f}u, junction {bd['junction']} -> join {bd['join']}, {types}")
    print("wrote", out)
