#!/usr/bin/env python3
"""Generate plugin/cs_party_tips.inc from web/public/tips.json (the one tip catalog). Run after editing tips.json."""
import json, os, sys
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tips = json.load(open(os.path.join(root, "web/public/tips.json")))["tips"]
ON = ["event", "shop", "armory", "camper", "duel", "vip", "negot", "site"]   # order = TIPON_* in the plugin
DEV = {None: 0, "kbd": 1, "touch": 2, "pad": 3}
WHEN = {"turn": 1, "wait": 2}
MAXLEN = 100   # HUD wraps at 30 (PC) / 36 (phone) characters; 4 lines
ids = set()
for t in tips:
    assert t["id"] not in ids, "duplicate id " + t["id"]; ids.add(t["id"])
    assert len(t["text"]) <= MAXLEN, "too long (%d): %s" % (len(t["text"]), t["id"])
    assert "^" not in t["text"] and "\n" not in t["text"]
    assert t.get("on") in ON + [None] and t.get("dev") in DEV
    assert all(w in WHEN for w in t.get("when", []))
esc = lambda s: s.replace('"', '^"')
first = [i for i, t in enumerate(tips) if t.get("first") == "turn"]
out = ["// GENERATED by tools/gen_tips.py from web/public/tips.json. Do not edit.",
       "#define TIP_N %d" % len(tips),
       "#define TIP_FIRST_TURN %d" % (first[0] if first else -1),
       "new const TIP_TEXT[TIP_N][] = {"]
out += ['\t"%s"%s' % (esc(t["text"]), "," if i < len(tips) - 1 else "") for i, t in enumerate(tips)]
out += ["};",
        "new const TIP_ON[TIP_N] = { %s };" % ", ".join(str(ON.index(t["on"]) + 1 if t.get("on") else 0) for t in tips),
        "new const TIP_WHEN[TIP_N] = { %s };" % ", ".join(str(sum(WHEN[w] for w in t.get("when", []))) for t in tips),
        "new const TIP_DEV[TIP_N] = { %s };" % ", ".join(str(DEV[t.get("dev")]) for t in tips), ""]
open(os.path.join(root, "plugin/cs_party_tips.inc"), "w").write("\n".join(out))
print("wrote %d tips" % len(tips))
