$modelname "csp_case.mdl"
$cd "."
$cdtexture "."
$scale 1.0
$bodygroup "part"
{
 studio "card"
 studio "panel"
 studio "marker"
 studio "glow0"
 studio "glow1"
 studio "glow2"
 studio "glow3"
 studio "glow4"
}
$texturegroup skins
{
{ "card00.bmp" }
{ "card01.bmp" }
{ "card02.bmp" }
{ "card03.bmp" }
{ "card04.bmp" }
{ "card05.bmp" }
{ "card06.bmp" }
{ "card07.bmp" }
{ "card08.bmp" }
{ "card09.bmp" }
{ "card10.bmp" }
{ "card11.bmp" }
{ "card12.bmp" }
{ "card13.bmp" }
{ "card14.bmp" }
{ "card15.bmp" }
{ "card16.bmp" }
{ "card17.bmp" }
{ "card18.bmp" }
{ "card19.bmp" }
{ "card20.bmp" }
{ "card21.bmp" }
}
$sequence idle "idle" fps 1 loop
